// Runtime files only. Shared by native sync and the itch ZIP builder.
export const webFiles = [
  'index.html', 'styles.css', 'game.js', 'game-config.js', 'game-rules.js',
  'manifest.webmanifest', 'sw.js', 'privacy.html',
  'assets/app-icon-bird-v1.png',
  'assets/gurdwara-courtyard-pixel-v1.png',
  'assets/gurdwara-sunset-pixel-v1.png',
  'assets/gurdwara-dawn-pixel-v1.png',
  'assets/player-girl-pixel-v1.png',
  'assets/player-girl-fall-pixel-v1.png',
  'assets/player-girl-net-pixel-v2.png',
  'assets/player-boy-pixel-v1.png',
  'assets/player-boy-fall-pixel-v3.png',
  'assets/player-boy-net-pixel-v4.png',
  'assets/platform-grass-pixel-v1.png',
  'assets/platform-spring-pixel-v1.png',
  'assets/platform-moving-pixel-v1.png',
  'assets/platform-break-wood-pixel-v1.png',
  'assets/parshad-bowl-pixel-v3.png',
  'assets/khanda-token-pixel-v3.png',
  'assets/bird-pigeon-flap-pixel-v1.png',
  'assets/bird-sparrow-flap-pixel-v1.png',
  'assets/bird-swift-flap-pixel-v1.png',
  'assets/powerup-kara-pixel-v1.png',
  'assets/powerup-nishan-pixel-v1.png',
  'assets/dhal-shield-pixel-v1.png',
  'assets/falcon-save-pixel-v1.png',
  'assets/catch-net-hover-pixel-v1.png',
  'assets/finish-banner-hover-pixel-v1.png',
];
